### ISSUE TITLE
Compilation problem on Raspberry Pi2

### ISSUE THREAD

**Issue by yalnte** [ldallolio/NASTRAN-95#1]
Hi, thank you very much for making these updates available. I've tried this on x86 Ubuntu Linux and it works well. I've also tried on Raspberry Pi 2 with gfortran and using the bootstrap script and '-static' as a linker option but it gives a segmentation fault. Configure seems to be picking up the correct options. I'd welcome any advice to get it running. Thanks in advance.

**Comment by ldallolio** [comment]
Hi, I didn't test yet with "-static", I don't see why it shouldn't work... You might want to ask at "nastran@yahoogroups.com" too, I think that someone already compiled this for android so you might find better help there :-) Do you have any undefined symbols in the static executable? You can check this by using the "nm", "objdump", "readelf" and "strings" commands. I will have a look at is as soon as I will find a free weekend ;-)

**Comment by yalnte** [comment]
Thanks very much - I've now tried this and it doesn't look like there are any undefined symbols (but I'm still trying to understand the output here). Incidentally, when running "strace" I get the message:

`
execve("../mds/nastran", ["../mds/nastran"], [/* 45 vars */]) = -1 ENOMEM (Cannot allocate memory)
--- SIGSEGV (Segmentation fault) @ 0 (0) ---
+++ killed by SIGSEGV +++
./testpi.sh: line 34:  2617 Segmentation fault      strace ../mds/nastran
`
so I'm going to also have a look at the memory settings to see if that is the cause.

**Comment by yalnte** [comment]
Still working on this, but it looks like the hardcoded variable sizes  in the initialisation phase of nastrn.f cause the problem. I've tried smaller values and it now runs (albeit with error messages due to other things I've probably changed by mistake.)

So far:
`COMMON / ZZZZZZ / IZ(400000000)
      COMMON / DBM    / IDBBAS, IDBFRE, IDBDIR, INDBAS, INDCLR, INDCBP
     &,                 NBLOCK, LENALC, IOCODE, IFILEX, NAME,   MAXALC
     &,                 MAXBLK, MAXDSK, IDBLEN, IDBADR, IBASBF, INDDIR
     &,                 NUMOPN, NUMCLS, NUMWRI, NUMREA, LENOPC
      INCLUDE 'NASNAMES.COM'
      CHARACTER*80    SDSN
      EQUIVALENCE    ( ISYSTM, SYSTM )
      LENOPC = 400000000      
`

changed to:

`COMMON / ZZZZZZ / IZ(40000000)
      COMMON / DBM    / IDBBAS, IDBFRE, IDBDIR, INDBAS, INDCLR, INDCBP
     &,                 NBLOCK, LENALC, IOCODE, IFILEX, NAME,   MAXALC
     &,                 MAXBLK, MAXDSK, IDBLEN, IDBADR, IBASBF, INDDIR
     &,                 NUMOPN, NUMCLS, NUMWRI, NUMREA, LENOPC
      INCLUDE 'NASNAMES.COM'
      CHARACTER*80    SDSN
      EQUIVALENCE    ( ISYSTM, SYSTM )
      LENOPC = 40000000      
`
